language: cpp
dist: trusty
compiler:
    - gcc
before_install:
    - sudo apt-get install libsqlite3-dev cmake valgrind
script:
    - export COVERALLS_SERVICE_NAME=travis-ci
    - export COVERALLS_REPO_TOKEN=LBabWqujATyFxhPqivesbRufCubG1GKUc
    - cmake . -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON
    - make
    - make coveralls
    - valgrind --leak-check=full --trace-children=yes ctest -V # Make sure tests are executed corretly and logged with "-V"
